django_kursovaya/blog/urls.py
from django.urls import path
from .views import BlogPostListView, BlogPostDetailView, BlogPostCreateView, BlogPostUpdateView, BlogPostDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogPostListView.as_view(), name='blog_list'),
    path('<int:pk>/', BlogPostDetailView.as_view(), name='blog_detail'),
    path('create/', BlogPostCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogPostUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogPostDeleteView.as_view(), name='blog_delete'),
]

django_kursovaya/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('users.urls')),
    path('', include('mailings.urls')),  # Для главной страницы
    path('blog/', include('blog.urls', namespace='blog')),
    path('mailing_service/', include('mailing_service.urls', namespace='mailing_service')),  # Обрати внимание на нижнее подчеркивание!
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_kursovaya/mailing_service/urls.py
from django.urls import path
from .views import (MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView,
                    ClientListView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView,
                    MailingSettingsListView, MailingSettingsCreateView, MailingSettingsDetailView,
                    MailingSettingsUpdateView, MailingSettingsDeleteView, MailingAttemptListView, ReportView,
                    block_client_view, unblock_client_view)


app_name = 'mailing_service'


urlpatterns = [
    path('clients/', ClientListView.as_view(), name='clients'),
    path('client/create/', ClientCreateView.as_view(), name='create_client'),
    path('client/<int:pk>/', ClientDetailView.as_view(), name='view_client'),
    path('client/<int:pk>/update/', ClientUpdateView.as_view(), name='update_client'),
    path('client/<int:pk>/delete/', ClientDeleteView.as_view(), name='delete_client'),

    path('client/<int:pk>/block/', block_client_view, name='block_client'),
    path('client/<int:pk>/unblock/', unblock_client_view, name='unblock_client'),


    path('messages/', MessageListView.as_view(), name='messages'),
    path('message/create/', MessageCreateView.as_view(), name='create_message'),
    path('message/<int:pk>/', MessageDetailView.as_view(), name='view_message'),
    path('message/<int:pk>/update/', MessageUpdateView.as_view(), name='update_message'),
    path('message/<int:pk>/delete/', MessageDeleteView.as_view(), name='delete_message'),


    # Уникальные пути для рассылок
    path('settings/', MailingSettingsListView.as_view(), name='settings'),
    path('setting/create/', MailingSettingsCreateView.as_view(), name='create_setting'),
    path('setting/<int:pk>/', MailingSettingsDetailView.as_view(), name='view_setting'),
    path('setting/<int:pk>/update/', MailingSettingsUpdateView.as_view(), name='update_setting'),
    path('setting/<int:pk>/delete/', MailingSettingsDeleteView.as_view(), name='delete_setting'),

    #Попытки рассылок
    path('setting/<int:pk>/attempts/', MailingAttemptListView.as_view(), name='attempts'),

    path('reports/', ReportView.as_view(), name='report'),  # Маршрут для отчёта
]

django_kursovaya/users/urls.py
from django.urls import path
from .views import login_view, register_view, profile_view, logout_view

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('profile/', profile_view, name='profile'),
    path('logout/', logout_view, name='logout'),
]

django_kursovaya/templates/includes/inc_menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="/">Главная</a>
   <div class="collapse navbar-collapse">
       <ul class="navbar-nav mr-auto">
           <li class="nav-item">
               <a class="nav-link" href="{% url 'blog:blog_list' %}">Блог</a>
           </li>
           {% if user.is_authenticated %}
               {% if user.is_staff %}
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:clients' %}">Клиенты</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:messages' %}">Сообщения</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:settings' %}">Рассылки</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:report' %}">Отчеты</a>
                   </li>
               {% elif user.groups.all.0.name == 'Manager' %}
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:clients' %}">Клиенты</a>
                   </li>
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:settings' %}">Рассылки</a>
                   </li>
               {% elif user.groups.all.0.name == 'Client' %}
                   <li class="nav-item">
                       <a class="nav-link" href="{% url 'mailing_service:clients' %}">Мои клиенты</a>
                   </li>
                   <li class="nav-item">
                       <!-- Обычный пользователь может просматривать свои рассылки -->
                       <a class="nav-link" href="{% url 'mailing_service:settings' %}">Мои рассылки</a>
                   </li>
               {% endif %}
               <!-- Кнопка "Мои сообщения" для всех авторизованных пользователей -->
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'mailing_service:messages' %}">Сообщения</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:profile' %}">Профиль</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:logout' %}">Выход</a>
               </li>
           {% else %}
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:login' %}">Вход</a>
               </li>
               <li class="nav-item">
                   <a class="nav-link" href="{% url 'accounts:register' %}">Регистрация</a>
               </li>
           {% endif %}
       </ul>
   </div>
</nav>